### ISSUE TITLE
Run ”mvn package exec:java“ failed

### ISSUE THREAD

**Issue by tbfly** [berndruecker/customer-onboarding-camundacloud-springboot-extended#1]
customer-onboarding-camundacloud-springboot: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java are missing or invalid.

**Comment by berndruecker** [comment]
Good catch - copy and pasted readme parts, but locally I just started via IDE. Fixed via https://github.com/berndruecker/customer-onboarding-camundacloud-springboot-extended/commit/23ca7036916550e9ab05c7b054cb3fae86d47ca1 - thx for reporting!
